- ignore: {name: Use String}
- ignore: {name: Use fewer imports}
- ignore: {name: Use lambda-case}
- ignore: {name: Use infix} # isPrefixOf
- ignore: {name: Redundant $}
- ignore: {name: Redundant do}
- ignore: {name: Use tuple-section}
- ignore: {name: Use const}
- ignore: {name: Too strict maybe}
- ignore: {name: "Use :"}
- ignore: {name: "Move guards forward"}
- ignore: {name: "Avoid lambda using `infix`"}
- ignore: {name: "Fuse foldr/map"}
- ignore: {name: Unused LANGUAGE pragma}
- ignore: {name: "Use <$>"}
- ignore: {name: Reduce duplication}
- ignore: {within: HaskellCI.Bash.Template}
- ignore: {name: Use camelCase}
