- ignore: {name: Use String}
- ignore: {name: Use fewer imports}
- ignore: {name: Use lambda-case}
- ignore: {name: Use infix} # isPrefixOf
- ignore: {name: Redundant $}
- ignore: {name: Redundant do}
- ignore: {name: Use tuple-section}
- ignore: {name: Use const}
- ignore: {name: "Use :"}
